---
# https://docs.sourcery.ai/Configuration/Project-Settings/
version: '1'
ignore:
- .git
- .venv

rule_settings:
  python_version: '3.10'
  enable:
  - default
  disable: []
  rule_types:
  - refactoring
  - suggestion
  - comment
